# Numpy
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

In [1]:
import numpy as np

In [2]:
list = [1, 2, 3, 4, 5, 6, 7, 8]
arr = np.array(list)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr.shape

(8,)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.dtype

dtype('int64')

In [10]:
arr2 = arr.reshape(2, 4)

In [13]:
arr2.shape

(2, 4)

## Indexing

In [17]:
arr[0]  # Accessing the first element

np.int64(1)

In [20]:
arr[2:6]  # Accessing elements from index 2 to 5

array([3, 4, 5, 6])

In [22]:
arr2[0, 0]  # Accessing the first element of the reshaped 2d array

np.int64(1)

In [23]:
arr2[:,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr3 = np.arange(1, 13).reshape(3, 4)

In [25]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr3[2,:] = 12 # Accessing the third row

In [28]:
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [12, 12, 12, 12]])

In [30]:
arr3[arr3>11] # Accessing elements greater than 11

array([12, 12, 12, 12])

In [32]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [34]:
arr * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
arr4 = np.ones((2,5), dtype=int) # Creating a 2x5 array filled with ones

In [36]:
arr4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
arr5 = np.random.rand(3, 4) # Random 3x4 array
arr5

array([[0.01246792, 0.03514672, 0.73251369, 0.26612545],
       [0.98966293, 0.69115725, 0.39133572, 0.35760538],
       [0.78600204, 0.64329252, 0.7334211 , 0.20589102]])

In [39]:
arr6 = np.random.randn(3, 3) # Random 3x3 array with standard normal distribution
arr6

array([[-0.83719485, -1.98903121,  1.65363388],
       [-1.16164068, -0.61348323,  0.23435866],
       [ 0.00502225, -1.47911816,  0.18545323]])